;; Adapter around the unmodified CLWFK generator. No replacement glyph geometry.
(in-package :cl-user)
(setf *debugger-hook* (lambda (condition hook) (declare (ignore hook)) (format *error-output* "ERROR: ~A~%" condition) (ext:quit :status 1)))
(defvar base-directory)
(defparameter source-load t)
(defun load-directory (dir) (let ((base-directory dir)) (load (concatenate 'string dir "/load.l"))))
(load-directory "engine/compatible/renderer")
(load-directory "engine/compatible/primdata")
(load-directory "engine/compatible/jointdata")
(load-directory "engine/compatible/kanjidata")
(defvar *bridge-out* *standard-output*)
(defun json-string (s)
 (write-char #\" *bridge-out*)
 (loop for c across s do (case c (#\" (write-string "\\\"" *bridge-out*)) (#\\ (write-string "\\\\" *bridge-out*)) (#\Newline (write-string "\\n" *bridge-out*)) (otherwise (write-char c *bridge-out*))))
 (write-char #\" *bridge-out*))
(defun json-value (v)
 (cond ((null v) (write-string "[]" *bridge-out*))
       ((stringp v) (json-string v))
       ((symbolp v) (json-string (string-downcase (symbol-name v))))
       ((integerp v) (format *bridge-out* "~D" v))
       ((numberp v) (format *bridge-out* "~,8F" v))
       ((listp v) (write-char #\[ *bridge-out*) (loop for item in v for i from 0 do (when (> i 0) (write-char #\, *bridge-out*)) (json-value item)) (write-char #\] *bridge-out*))
       (t (json-string (princ-to-string v)))))
(defun smooth (x) (let ((v (max 0d0 (min 1d0 x)))) (* v v (- 3 (* 2 v)))))
;; Upstream build scripts call rm-limit; this snapshot no longer defines it.
;; xlimit/ylimit are composition constraints, explicitly not drawable strokes.
(defun rm-limit (skel)
 (list* (first skel) (remove-if (lambda (s) (member (first s) '(xlimit ylimit))) (second skel)) (cddr skel)))
(defun char-symbol (code)
 (let* ((c (code-char code)) (direct (and c (find-symbol (string c)))))
  (cond ((and direct (boundp direct)) direct)
        ((<= 33 code 126) (find-symbol (string (code-char (+ code #xfee0)))))
        (t nil))))

(defun sexpr-text (value) (let ((*print-pretty* nil) (*print-readably* nil)) (prin1-to-string value)))
(defun exported-skeleton (skel)
 (list (mapcar (lambda(p)(list (first p)(second p)(sexpr-text (cddr p)))) (first skel))
       (mapcar (lambda(s)(list (first s)(second s)(sexpr-text (cddr s)))) (second skel))
       (sexpr-text (cddr skel))))
(let ((results nil))
 (dolist (code '(12354 27704 26408 26519 12290 19968 30000))
  (let* ((sym (char-symbol code)) (gothicwidth 8.0) (minchowidth 8.0) (local_gothicwidth 8.0) (local_minchowidth 8.0)
         (definition (get-def sym 'maru))
         (expanded (applykanji sym 'maru))
         (normalized (normkanji (rm-limit (copy-tree expanded))))
         (outline (skeleton2list (copy-tree normalized) 'maru)))
   (push (list (string (code-char code)) (sexpr-text definition)
               (exported-skeleton expanded) (exported-skeleton normalized) outline) results)))
 (with-open-file (*bridge-out* "source-audit/source-glyphs.raw.json" :direction :output :if-exists :supersede :external-format :utf-8)
   (json-value (nreverse results))))
(ext:quit)


