;; Adapter around the unmodified CLWFK generator. No replacement glyph geometry.
(in-package :cl-user)
(setf *debugger-hook* (lambda (condition hook) (declare (ignore hook)) (format *error-output* "ERROR: ~A~%" condition) (ext:quit :status 1)))
(defvar base-directory)
(defparameter source-load t)
(defun load-directory (dir) (let ((base-directory dir)) (load (concatenate 'string dir "/load.l"))))
(load-directory "engine/compatible/renderer")
(load-directory "engine/compatible/primdata")
(load-directory "engine/compatible/jointdata")
(load-directory "engine/compatible/kanjidata")
(defvar *bridge-out* *standard-output*)
(defun json-string (s)
 (write-char #\" *bridge-out*)
 (loop for c across s do (case c (#\" (write-string "\\\"" *bridge-out*)) (#\\ (write-string "\\\\" *bridge-out*)) (#\Newline (write-string "\\n" *bridge-out*)) (otherwise (write-char c *bridge-out*))))
 (write-char #\" *bridge-out*))
(defun json-value (v)
 (cond ((null v) (write-string "[]" *bridge-out*))
       ((stringp v) (json-string v))
       ((symbolp v) (json-string (string-downcase (symbol-name v))))
       ((integerp v) (format *bridge-out* "~D" v))
       ((numberp v) (format *bridge-out* "~,8F" v))
       ((listp v) (write-char #\[ *bridge-out*) (loop for item in v for i from 0 do (when (> i 0) (write-char #\, *bridge-out*)) (json-value item)) (write-char #\] *bridge-out*))
       (t (json-string (princ-to-string v)))))
(defun smooth (x) (let ((v (max 0d0 (min 1d0 x)))) (* v v (- 3 (* 2 v)))))
;; Upstream build scripts call rm-limit; this snapshot no longer defines it.
;; xlimit/ylimit are composition constraints, explicitly not drawable strokes.
(defun rm-limit (skel)
 (list* (first skel) (remove-if (lambda (s) (member (first s) '(xlimit ylimit))) (second skel)) (cddr skel)))
(defun char-symbol (code)
 (let* ((c (code-char code)) (direct (and c (find-symbol (string c)))))
  (cond ((and direct (boundp direct)) direct)
        ((<= 33 code 126) (find-symbol (string (code-char (+ code #xfee0)))))
        (t nil))))
(defun glyph-sequence (code style weight serif contrast steps)
 (let* ((sym (char-symbol code)))
  (unless (and sym (boundp sym)) (return-from glyph-sequence (list code "missing")))
  (let* ((minchowidth (float weight)) (gothicwidth (float weight))
         (skel (normkanji (rm-limit (applykanji sym style)))) (frames nil))
   (unless (and skel (car skel)) (return-from glyph-sequence (list code "missing")))
   (dotimes (i steps)
    (let* ((time (/ i (float (1- steps))))
           (growth (smooth time)) (ornament (* serif (+ .08 (* .92 (smooth (/ (- time .35) .65))))))
           (minchowidth (* weight (+ .10 (* .90 growth))))
           (gothicwidth minchowidth)
           (hirawidth (* minchowidth .05))
           (tateyokoratio contrast)
           (tatekazari (* 1.5 ornament)) (tomeheight (* 1.8 ornament)) (kazariheight (* 1.4 ornament)))
     ;; Each frame executes the original stroke, junction and terminal generators.
     (push (if (= i 0) nil (skeleton2list (copy-tree skel) style)) frames)))
   (list code (char-code (char (symbol-name sym) 0))
         (mapcar (lambda (p) (list (first p) (second p))) (first skel))
         (mapcar (lambda (s) (list (first s) (second s))) (second skel))
         (nreverse frames)))))
(let ((count 0)) (do-symbols (sym :cl-user) (when (and (= 1 (length (symbol-name sym))) (boundp sym) (consp (symbol-value sym))) (incf count))) (format t "READY ~D~%" count) (force-output))
(loop for line = (read-line *standard-input* nil nil) while line do
 (handler-case
  (let* ((*read-eval* nil) (request (read-from-string line))
         (codes (first request)) (style (nth (second request) '(mincho gothic maru)))
         (weight (third request)) (serif (fourth request)) (contrast (fifth request)) (steps (sixth request))
         (results nil))
   (dolist (code codes)
    (push (handler-case
           (let ((*standard-output* (make-broadcast-stream))) (glyph-sequence code style weight serif contrast steps))
           (error (e) (list code "error" (princ-to-string e)))) results))
   (write-char #\@ *bridge-out*) (json-value (nreverse results)) (terpri *bridge-out*) (force-output *bridge-out*))
  (error (e) (write-char #\@ *bridge-out*) (json-value (list "error" (princ-to-string e))) (terpri *bridge-out*) (force-output *bridge-out*))))
