;; Adapter around the unmodified CLWFK generator. No replacement glyph geometry.
(in-package :cl-user)
(setf *debugger-hook* (lambda (condition hook) (declare (ignore hook)) (format *error-output* "ERROR: ~A~%" condition) (ext:quit :status 1)))
(defvar base-directory)
(defparameter source-load t)
(defun load-directory (dir) (let ((base-directory dir)) (load (concatenate 'string dir "/load.l"))))
(load-directory "engine/compatible/renderer")
(load-directory "engine/compatible/primdata")
(load-directory "engine/compatible/jointdata")
(load-directory "engine/compatible/kanjidata")
(defvar *bridge-out* *standard-output*)
(defun json-string (s)
 (write-char #\" *bridge-out*)
 (loop for c across s do (case c (#\" (write-string "\\\"" *bridge-out*)) (#\\ (write-string "\\\\" *bridge-out*)) (#\Newline (write-string "\\n" *bridge-out*)) (otherwise (write-char c *bridge-out*))))
 (write-char #\" *bridge-out*))
(defun json-value (v)
 (cond ((null v) (write-string "[]" *bridge-out*))
       ((stringp v) (json-string v))
       ((symbolp v) (json-string (concatenate (quote string) (if (keywordp v) ":" "") (string-downcase (symbol-name v)))))
       ((integerp v) (format *bridge-out* "~D" v))
       ((numberp v) (format *bridge-out* "~,8F" v))
       ((listp v) (write-char #\[ *bridge-out*) (loop for item in v for i from 0 do (when (> i 0) (write-char #\, *bridge-out*)) (json-value item)) (write-char #\] *bridge-out*))
       (t (json-string (princ-to-string v)))))
(defun smooth (x) (let ((v (max 0d0 (min 1d0 x)))) (* v v (- 3 (* 2 v)))))
;; Upstream build scripts call rm-limit; this snapshot no longer defines it.
;; xlimit/ylimit are composition constraints, explicitly not drawable strokes.
(defun rm-limit (skel)
 (list* (first skel) (remove-if (lambda (s) (member (first s) '(xlimit ylimit))) (second skel)) (cddr skel)))
(defun char-symbol (code)
 (let* ((c (code-char code)) (direct (and c (find-symbol (string c)))))
  (cond ((and direct (boundp direct)) direct)
        ((<= 33 code 126) (find-symbol (string (code-char (+ code #xfee0)))))
        (t nil))))


(defun expand-browser (form)
 (cond ((atom form) form)
       ((eq (car form) 'quote) form)
       ((eq (car form) 'defun) (append (subseq form 0 3) (mapcar #'expand-browser (cdddr form))))
       ((eq (car form) 'lambda) (append (subseq form 0 2) (mapcar #'expand-browser (cddr form))))
       ((member (car form) '(let let* do do*))
        (list* (car form) (mapcar (lambda (b) (if (consp b) (cons (car b)(mapcar #'expand-browser (cdr b))) b)) (cadr form))
         (if (member (car form) '(do do*)) (cons (mapcar #'expand-browser (caddr form)) (mapcar #'expand-browser (cdddr form))) (mapcar #'expand-browser (cddr form)))))
       ((member (car form) '(cond case ecase))
        (if (eq (car form) 'cond) (cons (car form)(mapcar (lambda(c)(mapcar #'expand-browser c))(cdr form)))
         (list* (car form)(expand-browser (cadr form))(mapcar (lambda(c)(cons (car c)(mapcar #'expand-browser(cdr c))))(cddr form)))))
       ((and (symbolp (car form)) (macro-function (car form))
             (not (member (car form) '(defun defvar defparameter let let* cond and or when unless do do* dotimes dolist loop case ecase setf incf decf push pop return prog1 prog2))))
        (expand-browser (macroexpand-1 form)))
       (t (mapcar (function expand-browser) form))))
(defun ast-json (v)
 (cond ((null v)(write-string "null" *bridge-out*))
       ((symbolp v)(write-string "{\"s\":" *bridge-out*)(json-string (concatenate (quote string) (if (keywordp v) ":" "") (string-downcase (symbol-name v))))(write-char #\} *bridge-out*))
       ((or (numberp v)(stringp v))(json-value v))
       ((consp v)
        (let ((items nil)(tail v))
         (loop while (consp tail) do (push (car tail) items)(setq tail (cdr tail)))
         (when tail (write-string "{\"head\":" *bridge-out*))
         (write-char #\[ *bridge-out*)
         (loop for x in (nreverse items) for i from 0 do (when (> i 0)(write-char #\, *bridge-out*))(ast-json x))
         (write-char #\] *bridge-out*)
         (when tail (write-string ",\"tail\":" *bridge-out*)(ast-json tail)(write-char #\} *bridge-out*))))
       ((vectorp v)(write-string "{\"vector\":" *bridge-out*)(ast-json (coerce v 'list))(write-char #\} *bridge-out*))
       (t(error "Cannot export ~S" v))))
(let ((forms nil))
 (dolist (file '("compat.l" "lib.l" "pack.l" "limit.l" "limitrule.l" "transform.l" "region.l" "unit.l" "yokosort.l" "center.l" "newjoint.l" "apply.l" "outline.l" "skel2list.l" "mincho.l" "gothic.l" "maru.l" "interpol.l" "mincho2.l" "hiranew.l" "sym.l"))
  (with-open-file (stream (concatenate 'string "engine/compatible/renderer/" file) :external-format :utf-8)
   (loop for form = (read stream nil :eof) until (eq form :eof) do
    (when (and (consp form)(member (car form) '(defun defvar defparameter defelement deftypehook defkazari subfont setq putprop)))
     (push (expand-browser form) forms)))))
 (with-open-file (*bridge-out* "web/source-program.json" :direction :output :if-exists :supersede :external-format :utf-8)(ast-json (nreverse forms))))

(defun contains-function (v) (cond ((functionp v)t)((consp v)(or(contains-function(car v))(contains-function(cdr v))))))

(let ((glyphs nil)(gothicwidth 8.0)(minchowidth 8.0)(local_gothicwidth 8.0)(local_minchowidth 8.0))
(dolist (code '(12354 27704 26408 26519 12290 19968 30000))
 (let* ((s(char-symbol code))(sk(normkanji(rm-limit(applykanji s 'maru))))(clean(list* (car sk)(cadr sk)(remove-if #'contains-function(cddr sk)))))
 (push (list (symbol-name s) clean) glyphs)))
(with-open-file (*bridge-out* "source-audit/source-fixture.json" :direction :output :if-exists :supersede :external-format :utf-8)(ast-json glyphs)))
(ext:quit)
