import {NativeRenderer as FoldRenderer} from './native-renderer.js';
import {loadSourceEngine} from './source-engine.js';
import {missingCharacters} from './font-support.js';
const $=id=>document.getElementById(id);
const variants=[10,11,11,10];
const patterns=[['06 トリムなし',''],['06 横軸と関節',''],['06 円弧トリム＋関節',''],['隣へ受け渡す','']];
let metadata,clock=0,last=0,globalToken=0;const cards=[];
function bindInput(input,callback,onCompositionStart=()=>{}){let timer,composing=false;const schedule=()=>{clearTimeout(timer);timer=setTimeout(callback,70)};input.addEventListener('compositionstart',()=>{composing=true;clearTimeout(timer);onCompositionStart()});input.addEventListener('compositionend',()=>{composing=false;schedule()});input.addEventListener('input',()=>{if(!composing)schedule()});}
async function update(card,text,replay=false){const token=++card.token;const missing=[...new Set(Array.from(text).filter(c=>c.trim()&&!metadata.resolve(c)))];card.error.textContent=missing.length?`未収録：${missing.join('・')}`:'';const safe=Array.from(text).map(c=>missing.includes(c)?' ':c).join('');try{await card.renderer.setText(safe,()=>token===card.token,()=>clock);}catch(e){card.error.textContent=e.message;return;}if(token!==card.token)return;if(replay)card.renderer.replay(clock);card.canvas.dataset.glyphs=String(card.renderer.placed.length);const glyphs=[...card.renderer.cache.values()].filter(g=>card.renderer.items.some(i=>i.glyph===g)),graphs=glyphs.map(g=>g.strategy.graph);card.stats.textContent=`原典 ${glyphs.reduce((n,g)=>n+g.strokes.length,0)}画 / 共有点 ${graphs.reduce((n,g)=>n+g.nodes.filter(v=>v.edges.length>=2).length,0)}`;const notices=[...new Set(glyphs.filter(g=>g.strategy.notice).map(g=>g.text+"："+g.strategy.notice))];if(!missing.length)card.error.textContent=notices.join('・');}
function replayAll(){for(const card of cards)card.renderer.replay(clock);}
async function updateAll(){if(!metadata)return;const token=++globalToken,text=$('common').value;for(const card of cards)card.input.value=text;await Promise.all(cards.map(card=>update(card,text)));if(token===globalToken)replayAll();}
function frame(now){if(last&&!document.hidden&&!$('license').open)clock+=Math.min(.1,(now-last)/1000)*Number($('speed').value);last=now;if(!document.hidden&&!$('license').open){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,expanded=document.querySelector('.pattern.expanded');for(const card of cards){if(expanded&&card.canvas.closest('.pattern')!==expanded)continue;const bounds=card.canvas.parentElement.getBoundingClientRect();if(bounds.bottom<0||bounds.top>innerHeight)continue;card.renderer.draw(clock,{staticAmount:$('manual').checked?Number($('fold').value):reduced?0:null});drawGuides(card);if(card.canvas.dataset.renderError)card.error.textContent=card.canvas.dataset.renderError;}}requestAnimationFrame(frame);}
$('replay-all').disabled=true;$('replay-all').onclick=()=>{$('manual').checked=false;replayAll()};$('speed').onchange=replayAll;
bindInput($('common'),updateAll,()=>{++globalToken;for(const card of cards)++card.token;});
$('info').onclick=async()=>{$('license').showModal();try{const r=await fetch('/LICENSE.txt');if(!r.ok)throw Error();$('license-text').textContent=await r.text();}catch{$('license-text').textContent='ライセンスを読み込めませんでした。'}};$('close').onclick=()=>$('license').close();$('license').addEventListener('click',e=>{if(e.target!==$('license'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();});
addEventListener('resize',()=>cards.forEach(card=>card.renderer.layout()));
async function initialize(){try{metadata=await loadSourceEngine();for(let i=0;i<patterns.length;i++){const [name,description]=patterns[i],section=document.createElement('section');section.className='pattern';section.innerHTML=`<div class="pattern-head"><h2><span class="number">${["B","C","C＋","B→"][i]}</span>${name}</h2><button aria-label="${name}を再生">再生</button></div><p class="description">${description}</p><div class="stage"><canvas role="img" aria-label="${name}のプレビュー"></canvas></div><input class="trial" aria-label="${name}に試打" autocomplete="off" spellcheck="false"><p class="stats"></p><p class="error" role="status"></p>`;$('patterns').append(section);const canvas=section.querySelector('canvas'),input=section.querySelector('input'),renderer=new FoldRenderer(canvas,{compact:true,fontSize:Number($('letter-size').value),variant:variants[i],structural:true,roundTrim:i===2,relay:i===3});const card={canvas,input,renderer,error:section.querySelector('.error'),stats:section.querySelector('.stats'),token:0};const overlay=document.createElement('canvas');overlay.className='guides';section.querySelector('.stage').append(overlay);card.overlay=overlay;cards.push(card);
 const expand=document.createElement('button');expand.textContent='拡大';expand.setAttribute('aria-label',`${name}を拡大`);section.querySelector('.pattern-head').append(expand);
 const sizeControl=document.createElement('label');sizeControl.className='expanded-size';sizeControl.textContent='文字サイズ ';const sizeInput=document.createElement('input');sizeInput.type='range';sizeInput.min='48';sizeInput.max='240';sizeInput.step='4';sizeInput.value='128';sizeInput.setAttribute('aria-label',`${name}の文字サイズ`);sizeControl.append(sizeInput);section.querySelector('.pattern-head').append(sizeControl);sizeInput.oninput=()=>{renderer.options.fontSize=Number(sizeInput.value);renderer.layout();};
 expand.onclick=()=>{const opening=!section.classList.contains('expanded');document.querySelectorAll('.pattern.expanded').forEach(s=>s.classList.remove('expanded'));document.querySelectorAll('.expand-active').forEach(b=>{b.textContent='拡大';b.classList.remove('expand-active')});if(opening){section.classList.add('expanded');expand.textContent='戻る';expand.classList.add('expand-active');}renderer.options.fontSize=opening?Number(sizeInput.value):Number($('letter-size').value);renderer.layout();renderer.replay(clock);};
 input.value=$('common').value;bindInput(input,()=>update(card,input.value),()=>++card.token);section.querySelector('button').onclick=()=>{$('manual').checked=false;renderer.replay(clock)};}
 await updateAll();$('status').textContent='';$('replay-all').disabled=false;requestAnimationFrame(frame);
 }catch(e){$('status').textContent=e.message;}}
initialize();

function drawGuides(card){const canvas=card.overlay,r=card.renderer;if(!$('guides').checked){canvas.hidden=true;return;}canvas.hidden=false;if(canvas.width!==r.canvas.width||canvas.height!==r.canvas.height){canvas.width=r.canvas.width;canvas.height=r.canvas.height;}canvas.style.height=`${r.height}px`;canvas.style.top=`${r.canvas.parentElement.scrollTop}px`;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);if(!$('guides').checked)return;ctx.save();ctx.scale(canvas.width/r.width,canvas.height/r.height);for(const item of r.placed??[]){const scale=item.size/item.glyph.pixelFontSize;for(const p of item.glyph.strategy.anchors){ctx.beginPath();ctx.arc(item.x+(p.x/.64-200)*scale,item.y-r.canvas.parentElement.scrollTop+(p.y/.64-200)*scale,2.5,0,Math.PI*2);ctx.fillStyle='#357fbd';ctx.fill();}}ctx.restore();}
$('fold').oninput=()=>{$('manual').checked=true;};



$('letter-size').oninput=()=>{$('letter-size-value').textContent=$('letter-size').value;for(const card of cards){card.renderer.options.fontSize=Number($('letter-size').value);card.renderer.layout();}};
addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.expand-active')?.click();}});
